#!/bin/sh
#
# koha_zebra - basic rc.d script for koha
# Copyright 2010  Jared Camins-Esakov
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# PROVIDE: koha_zebra
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="koha_zebra"
rcvar=`set_rcvar`

load_rc_config $name

: ${koha_zebra_enable:=NO}
: ${koha_zebra_flags:=""}

command="/usr/local/bin/zebrasrv"
command_args="-D -v none,fatal,warn \
        -f \"/home/${koha_zebra_user}/koha-dev/etc/koha-conf.xml\""

run_rc_command "$1"
